source/index.md

Clear enough to eliminate the misunderstanding QP seems to have gotten?
@x2q @soltveit

Clarify that refunds does not "free up" capturable amount

---

source/index.md

Reference parameter

---

source/index.md

This should probably just be merged in without hesitation :-)
@ct-clearhaus It seems you authored most recently. Ok? :-)

Three very small fixes.

---

source/index.md

Add unsupported card scheme status code

---

source/index.md

* scheme may also be `unknown`
* country is omittable
* type is omittable

Adjust card representation

---

source/index.md

Csc response

---

source/index.md

Explain scheme's credit amount limits

---

source/index.md

The new MasterCard 2-series is included.

Fix explanation for test cards

---

source/index.md

Remove bin from example card response

---

source/index.md

The rendering b0rks when `</p>` is not on its own line it seems.

Fix formatting

---

source/index.md

Minor improvements

---

source/index.md

Pointed out by @noxern on Slack.

Fix country code letter count

---

source/index.md

Related to https://github.com/clearhaus/gateway-api-docs/pull/58 .
Pointed out by @noxern on Slack.

Change GBR country code to GB

---

source/index.md

@soltveit has ok'ed November 15, 2018.

Specify deprecation date for latest update

---

source/index.html.md

Please correct me if I'm wrong 🙂

Clarify that attempted 3DS is not SCA

---

.circleci/config.yml

Auto deploy to s3 when master is updated through circleci

Migrate docs.gateway.clearhaus.com to s3 via CircleCi

---

source/index.html.md

This is to indicate that the transaction should be accompanied by additional authentication. In practice, this can currently interpreted as "Retry with 3DS".

Add "step-up" response code

---

source/index.html.md

Prompted by https://github.com/clearhaus/issues-pci/issues/1321#issuecomment-571521073.

Make signing of POST requests mandatory

---

source/index.html.md

Cf. https://github.com/clearhaus/gateway-api-docs/pull/89#issuecomment-572486179

CSC is optional only when partner is trusted

---

source/index.html.md

Related to https://github.com/clearhaus/klovedal/pull/407 and https://github.com/clearhaus/visa-direct-connector/pull/18.
Draft PR as I am awaiting clarification from Visa regarding the format of the parameter.

Add optional name on card parameter

---

source/index.html.md

Notice: PR on clearhaus/gateway-api-docs#100
Feel free to merge or close without further ado 🙂

Samsung Pay Review

---

source/index.html.md

PR #100 was merged by accident by yours truly 🙂

Roll back add-samsungpay

---

source/index.html.md

Noticed by partner. Thanks! 🙇‍♂️

Fix wording for recurring

---

source/index.html.md

Explain that you need to be a partner to use the API.
Feel free to merge 🙂
Cc: @mep-clearhaus

Update "Getting Started"

---

source/index.html.md

Yes, it is expired, but that doesn't really matter.
Feel free to merge 🙂

Update link to HAL spec

---

source/index.html.md

@mep-clearhaus just told me that a new page was released 🤗
Feel free to merge 🙂

Update partner URL

---

source/index.html.md

Sorry for the low effort (I haven't tested anything), I just wanted to let you know before I forget. Feel free to close this PR if dealt with otherwise.

Update recurring example with regards to the PARes

---

.circleci/config.yml

Fix cicleci bug - wasn't able to install awscli
ref: https://clearhaus.slack.com/archives/C0H40P91P/p1622197084045700

Fix circleci awscli bug

---

source/index.html.md

Alternative to https://github.com/clearhaus/gateway-api-docs/pull/129. I'm a bit more fond of this, as the lines here don't look as much copy-pasty (the exact same parameters and notes for mail and telephone).

Add moto as new payment method

---

source/index.html.md

I *think* this is a clarification, and I *think* it's clear enough, but please be liberal with critics and suggestions 🙂

Clarify necessity of COF=store before MIT

---

source/index.html.md

Issue: https://github.com/clearhaus/issues-pci/issues/2243
Document the creation of an Apple Pay authorization from raw values from a payment token.

Raw Apple Pay

---

source/index.html.md

Notice that this is a PR on https://github.com/clearhaus/gateway-api-docs/pull/141!
Also some renaming suggestions, shortening of descriptions, etc.

Make the dict deeper

---

source/index.html.md

Project: https://github.com/clearhaus/issues-project-management/issues/32
Fact gathering and analysis of requirements: https://github.com/clearhaus/issues-project-management/issues/68
Travel: API Design discussion: https://github.com/clearhaus/issues-pci/issues/2499
Skeleton PR for adding TAD to the gateway API. This is intended to be used as a draft for further discussion and development. WIP.

Travel Addendum Data API design

---

source/index.html.md

Fixes https://github.com/clearhaus/gateway-api-docs/issues/143.

Correct regular expressions for amount

---

README.md
gulpfile.js
package.json
website/content/gateway/api_reference/resources/authorizations/authorizations.md
website/content/gateway/api_reference/resources/authorizations/authorizations_methods/card.md
website/content/gateway/api_reference/resources/authorizations/authorizations_methods/token.md
website/content/gateway/examples/3_d_sercure/secure_transactions/secure_transactions.md
website/content/gateway/examples/charge_a_cardholder/reserve_money/reserve_money.md
website/content/gateway/getting_started/signing_requests/signing_requests.md
website/layouts/index.html
yarn.lock

Fixes some of the vulnerabilities https://github.com/clearhaus/gateway-api-docs/security/dependabot
Furthermore, it fixes some error/typos in the markdown files e.g.

Update packages and docs

---

website/content/gateway/api_reference/resources/refunds/refunds.md

Use "Refunds" as title for the section about refunds :slightly_smiling_face: 
Feel free to merge after approval.

Fix incorrect title

---

website/content/gateway/api_reference/resources/authorizations/authorizations.md
website/content/gateway/api_reference/resources/authorizations/authorizations_methods/googlepay.md

Rendered (which doesn't reveal much):

Link to payment methods

---

website/content/gateway/api_reference/changes/changes.md
website/content/gateway/api_reference/resources/authorizations/authorizations_methods/googlepay.md

Google Pay payment method support for 3-D Secure

---

website/content/gateway/api_reference/resources/account/account.md

Closes https://github.com/clearhaus/issues-pci/issues/5132

Elaborate that the merchant currency is the funding currency

---

website/content/currencies.md

The the internal comment https://github.com/clearhaus/issues-pci/issues/5046#issuecomment-2376885829.

Sync currencies with Visa and Mastercard

---

website/content/gateway/api_reference/changes/changes.md

Issue: https://github.com/clearhaus/issues-pci/issues/5094

Document voiding of failed authorizations

---

website/content/gateway/api_reference/changes/changes.md
website/content/gateway/api_reference/resources/capture_refunds/capture_refunds.md

See the deployment issue linking to this.

Extend capture refund period
