clearhaus/gateway-api-docs

source/index.md
We are soon removing GET support for the account-wide collections, i.e. /authorizations, /captures, /refunds, /voids, /credits and /cards. Adjust the API documentation accordingly.
**Update (May 20):** All collection functionality is removed, not only account-wide.
@ct-clearhaus @soltveit RFR
=> No GET support on collection endpoints

source/index.md
Prompted by the following communication in the clearpay channel in QuickPay's Slack:
> kd: ct-clearhaus: ved du om i har noget info omkring jeres "40200: Clearhaus rule violation" hvad den dækker over, kunne ikke lige finde noget på jers docs
> ct-clearhaus: kd: vi svarer den regel tilbage som har udløst fejlkoden.
> ta: @aq_status_code="40200", @aq_status_msg="Clearhaus rule violation"
> ct-clearhaus: Det er ikke den "message" vi returnerer.
@ct-clearhaus @soltveit WDYT?
=> Rule violation examples

source/index.md
PSP has confused the card token functionality with subscriptions, especially wrt. 3-D Secure. This is an attempt to clarify.
RFR @soltveit @mt-clearhaus @proxygin
=> Adjust text regarding subscriptions

source/index.md
This is for consistency. Actually, `GET /account` is the only place we screwed up and named the account's descriptor `text_on_statement`.
The naming is that the account has a `descriptor` whereas a transaction has a `text_on_statement`. The account's `descriptor` is the default `text_on_statement` for all transactions if nothing is supplied in the `POST` to create the given transaction.
=> Account descriptor as `descriptor`

source/index.md
This error code will be used for transactions that are not possible.
For instance a subsequent recurring transaction for a Maestro card where the merchant has not been assigned a static AAV.
A detailed and descriptive `status.message` should be returned explaining the specific issue.
=> Add invalid transaction status code

source/index.md
We're seeing `19\d\d` be input as expire year and other "funny" numbers that are accepted as cards that will obviously never result in a successful transaction. Thus, let us throw these cards away earliest possible.
=> Require expire_year in this century

source/index.md
To avoid truncation by the stylesheet.
Before:
After:
I had no luck editing the stylesheets in `bower_components`.
=> Wrap MobilePay Online parameters

source/index.md
Actually, rewrite the entire section on test card numbers.
=> Correct status code as transaction amount

.circleci/config.yml
It appears installing `awscli` using `apt-get` has begun to fail consistently on CircleCI's Ubuntu 14.04 hosts.
```
sudo apt-get install awscli
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package awscli
Exited with code 100
```
This is inspired by https://docs.aws.amazon.com/cli/latest/userguide/install-linux.html#install-linux-awscli
=> Use pip to install awscli

source/index.html.md
Nobody has used them the last 90 days.
Nobody should be using them.
=> Remove GET endpoints

source/index.html.md
Using Ruby's IPAddr we check that an IP address is in fact a valid v4 or v6 address. It is therefore not sufficient to adhere to the regular expression.
A v6 address can be up to 45 characters long. We have this set correctly in the database layer.
=> Correct and clarify IP address format

source/index.html.md
=> Clarify that CSC matches false can mean no check

source/index.html.md
Announce that support for multiple signatures is removed on 2020-10-31. The date has not been determined yet.
=> Remove support for multiple signatures

source/index.html.md
Adding `cryptogram` and `eci` as optional parameters. Retaining MPO's ability to use non-token based PAN and 3DS.
This ensures backwards compatibility, MPO 3DSecure Fallback and Mastercard support.
For a more full fleshed integration we can opt for receiving the entire `tokenCallback` object from VTS. According to MPO docs, this is what the PSP's are expected to receive from VTS https://github.com/MobilePayDev/MobilePay-Online/pull/25/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R97-R134
This will have to be extended once we figure out what MPO plans to do with Mastercard.
This PR should be read en conjunction with 
* https://github.com/clearhaus/klovedal/pull/480
* https://github.com/clearhaus/authorizer/pull/173
=> Add minimalistic MPO API changes

source/index.html.md
A non-ASCII char had sneaked in:
=> Replace ' ' with ' '. Hex 00a0 vs. Hex 20

source/index.html.md
* `credential` to indicate if stored credential is being stored or used (or
irrelevant, by leaving it out)
* `initiator` to indicate what party initiate the authorization
* `series[]` to replace `recurring` but also extend with UCOF and
Clearhaus-internal and raw transaction reference to the previous-in-series
This PR supersedes:
* https://github.com/clearhaus/gateway-api-docs/pull/78
* https://github.com/clearhaus/gateway-api-docs/pull/79
* https://github.com/clearhaus/gateway-api-docs/pull/81
* https://github.com/clearhaus/gateway-api-docs/pull/83
=> Introduce credential, initiator and series[]

source/index.html.md
Apparently the old one is now in use in production; and the BIN range is a Maestro range which doesn't support recurrings.
=> Adjust the special test PAN

source/index.html.md
The names are:
DE48: Additional Data
DE48SE22: Multi-Purpose Merchant Indicator
DE48SE22SF01: Low-Risk Merchant Indicator
However, I think these are of no value in the documentation, so I decided to leave it out; at least it's better than indicate a naming that is wrong.
Courtesy of @absrd 🙇‍♂️
=> Bugfix Mastercard exemption values

source/index.html.md
This is building upon the design and decisions in https://github.com/clearhaus/gateway-api-docs/pull/111 and is thus heavily inspired by 3d0c2e5.
To be fixed:
* How to get to know this?
* By supplying ...
* (a) both `series[type]` and `series[previous][$scheme]`?
* (b) adding `series[previous][$scheme][type]` and thus supplying it "next to" `series[previous][$scheme][tid]`?
* (c) adding `series[previous][type]` and thus supplying it with `series[previuos][$scheme][tid]`?
* Required or optional? (If optional, what should be the default?)
=> Introduce unscheduled (UCOF) series

source/index.html.md
No matter if the first-in-series was made with `applepay`, `googlepay`, or `mobilepayonline`.
Courtesy of @jgivoni.
=> Clarify subsequent in series on same card

Gemfile.lock
For https://github.com/clearhaus/issues-pci/issues/2832, https://www.debian.org/security/2022/dsa-5146.
Fixes
- https://security-tracker.debian.org/tracker/CVE-2021-41136
- https://security-tracker.debian.org/tracker/CVE-2022-23634
- https://security-tracker.debian.org/tracker/CVE-2022-24790
=> Bump puma to 4.3.8

.circleci/config.yml, source/index.html.md
Notice that both version and variant are unchanged:
```
0a1b2c3d-4e5f-4c2f-9999-000000000000
version ---^    ^--- variant
```
* Version: 4, because hex char 13 is still a 4.
* Variant: 1, because hex char 17 is still 8-b.
=> Make the example signing API key less realistic

source/index.html.md
... when the transaction amount (which is used to trigger specific status codes) is not a valid status code.
=> Explain default behaviour for test pans

website/content/gateway/api_reference/changes/changes.md, website/content/gateway/api_reference/resources/authorizations/authorizations_methods/token.md
We do not consider `token[m4m]` and `token[vts]` to be two different payment methods. M4M and VTS are token frameworks living under the `token` payment method.
Feel free to merge.
=> Make token one payment method

website/content/gateway/api_reference/resources/authorizations/authorizations_methods/token.md
Remote Commerce Acceptor Identifier. At present only relevant for Mastercard, i.e. only for `token[m4m]`, not for `token[vts]`.
Rendered:
The two examples for the identifier are borrowed from Mastercard's Customer Interface Specification (DE104SE003).
I found the parameter for SCOF here:
https://developer.mastercard.com/secure-card-on-file/documentation/new-api-reference/apis/#checkout
I have established that the parameter is not present for MDES here:
https://developer.mastercard.com/mdes-digital-enablement/documentation/api-reference/
Mastercard writes that the parameter is "expected to be present in remote commerce transactions initiated via wallets or remote commerce programs that support DSRP cryptogram format 3". I have simplified this to "optional" as we do not dive into such …
=> Add optional token[m4m][rcai] parameter

website/content/gateway/api_reference/resources/authorizations/authorizations.md, website/content/gateway/api_reference/resources/credits/credits.md
The information can be derived from https://docs.gateway.clearhaus.com/#account -> `descriptor`, but let's just make it easier to stumble upon.
=> Explain default TOS value

website/content/gateway/api_reference/resources/authorizations/authorizations_methods/card.md
3dsecure.io url was wrong.
`https://wwww.3dsecure.io` => `https://www.3dsecure.io`
=> Update URL to 3dsecure.io

package.json, yarn.lock
Due to: https://github.com/clearhaus/gateway-api-docs/security/dependabot?q=is%3Aopen+manifest%3Ayarn.lock+package%3Ajson5
We don't use babel/core for anything so we can just remove it for now.
=> Remove babel/core

website/content/gateway/api_reference/transaction_status/transaction_status_codes_table.md
Fixes https://github.com/clearhaus/issues-pci/issues/3509.
I've went through klovedal `factory.rb` and `visa-direct.rb` to conduct which status codes are reachable.
I'm a bit pulsed about the `Invalid currency` as I suppose that the currency is inherited from the original debit.
=> Add Debit and Debit Refund to transaction status codes table

website/content/gateway/api_reference/endpoint_summary/endpoint_summary.md, website/content/gateway/api_reference/transaction_status/transaction_status_codes_table.md
I've found that we are missing some endpoint in Endpoint summary.
This will add them. Served locally:
=> Add refunds, debits and debit refunds to endpoint summary

website/content/gateway/api_reference/resources/debits/debits.md
Visa Direct does not allow for debits with amount zero. This will be stated by this update to our documentation.
I've remove the exception related to 3DSv1 as this was removed from the documentation elsewhere by https://github.com/clearhaus/gateway-api-docs/commit/a93ddde0210227935ccf129f192a29316f3c459f
=> Explicitly state that amount must be greater than zero.

website/content/gateway/api_reference/resources/credits/credits.md, website/content/gateway/examples/payout_to_cardholder/payout_to_cardholder.md
From the 6th of June payment of winnings for Mastercard will require name of recipient.
Internal link: https://github.com/clearhaus/issues-project-management/issues/102
=> Make name on card mandatory for POW for mastercard

website/content/gateway/api_reference/resources/authorizations/authorizations.md
Subsequent-in-series authorizations can be made using the token payment method.
=> Correct subsequent-in-series payment method error

website/content/gateway/api_reference/changes/changes.md, website/content/gateway/api_reference/resources/authorizations/authorizations_methods/card.md, website/content/gateway/api_reference/resources/credits/credits.md, website/content/gateway/api_reference/resources/debits/debits.md, website/content/gateway/api_reference/resources/debits/recipient_information.md, website/content/gateway/api_reference/resources/debits/sender_information.md
`recipient` concept added to `debits`. Adding `recipient[name]` and `recipient[account_number]` replaces `sender[account_number]`.
=> Add support for recipient information on `debits`

website/content/gateway/api_reference/resources/authorizations/authorizations.md
Only the "store" value was explained in text; the added text is addressing the "use" value.
=> Extend COF parameter explanation

website/content/gateway/api_reference/changes/changes.md, website/content/gateway/api_reference/resources/capture_refunds/capture_refunds.md, website/content/gateway/api_reference/resources/captures/captures.md
We are extending our API to support Visa's Foreign Retail Indicator (FRI) for marketplaces. We have chosen to rephrase this to `marketplace[interregional_retailer]`.
The parameter will be required when a merchant is a marketplace. The conditional requirement will be the same for both Visa and Mastercard.
=> Add `marketplace[interregional_retailer]` to captures and capture refunds

website/content/gateway/api_reference/resources/authorizations/authorizations_methods/googlepay.md
Related issue https://github.com/clearhaus/issues-pci/issues/4156#event-10765079084
New rendered version
As is
The note still state how to use it in test
I think this hints towards how to use it.
=> Update googlepay[recipient_id] description

website/content/gateway/api_reference/resources/debits/debits.md
The original reason for this was that debits are not supported for marketplace merchants, however, the more "general" reasoning is that our debits currently support funding transactions (on Visa cards).
=> Mention funding transactions in debits notice block

website/content/gateway/api_reference/changes/changes.md, website/content/gateway/api_reference/resources/authorizations/authorizations.md
To support the indication of a Transaction Risk Analysis (TRA) SCA exemption upstream.
Alternative to https://github.com/clearhaus/gateway-api-docs/pull/183.
=> Add sca_exemption parameter

website/content/gateway/api_reference/resources/authorizations/authorizations_methods/googlepay.md
We now support 3DSecure values for googlepay and the docs should reflect that change.
=> Add notice for liability shift for googlepay with 3ds

website/content/gateway/getting_started/rsa_signature/rsa_signature.md
For our partner folks' convenience so it's very easy to grab the public key when they're using it for setting up sandbox accounts.
=> Add the public part of the RSA key pair

website/content/gateway/examples/series_of_transactions/repeatedly_reserve_money/repeatedly_reserve_money.md
Various issues:
* Mention debit when authorization is mentioned.
* Mention `vipps` payment method.
* Change "the previous-in-series" to "a previous-in-series".
* Mention that `token[m4m/vts]` shall be used for subsequent-in-series on tokens.
<details>
<summary>Rendering</summary>
</details>
=> Fix repeatedly reserve money guidance

website/content/gateway/api_reference/changes/changes.md, website/content/gateway/api_reference/resources/authorizations/authorizations_methods/token.md
The parameter `token[m4m][eci]` is no longer necessary for the processing of `token[m4m]` authorizations.
=> Remove token[m4m][eci] parameter

website/content/gateway/api_reference/resources/authorizations/authorizations.md
This should hopefully avoid confusion on what to send in case there is no COF involved in the authorization.
=> Be explicit when no COF is involved

website/content/gateway/api_reference/changes/changes.md
It will be removed from the authorization response. This is only place where it is present.
Rendering:
=> Announce removal of threed_secure property

website/content/gateway/api_reference/resources/authorizations/authorizations_methods/applepay.md
This is currently the case and should be reflected by the API documentation.
Rendering:
=> Clarify applepay[raw][eci] is required for Visa

website/content/gateway/api_reference/resources/authorizations/authorizations_methods/mobilepayonline.md
For the `mobilepayonline` payment method.
An authorization made with `mobilepayonline` without a payment token no longer provides SCA.
=> Correct SCA notice for MobilePay Online

website/content/gateway/api_reference/changes/changes.md, website/content/gateway/api_reference/resources/authorizations/authorizations_methods/googlepay.md, website/content/gateway/api_reference/resources/credits/credits.md, website/content/gateway/api_reference/resources/debits/debits.md, website/content/gateway/api_reference/resources/debits/recipient_information.md
We are currently moving credits to the Mastercard MoneySend framework. As part
of this migration we are implementing debits for Mastercard. As part of this
some extra information is required.
=> Add Mastercard debits
